export const KLEND = {
  PROGRAM_ID: "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",
  SCOPE_ORACLE: "3t4JZcueEzTbVP6kLxXrL3VpWx45jDer4eqysweBchNH",
  LOOKUP_TABLE_ADDRESSES: ["284iwGtA9X9aLy3KsyV8uT2pXLARhYbiSi5SiM2g47M2"],
  MAIN_MARKET: {
    LENDING_MARKET: "7u3HeHxYDLhnCoErrtycNokbQYbWGzLs6JSDqGAv5PfF",
    USDC: {
      RESERVE: "D6q6wuQSrifJKZYpR1M8R4YawnLDtDsMmWM1NbBmgJ59",
    },
  },
};
